add command check

diff --git a/bin/ap-clients b/bin/ap-clients
--- a/bin/ap-clients
+++ b/bin/ap-clients
@@ -5,10 +5,28 @@
 # written for openwrt 12.09 Attitude Adjustment
 # modified by romano@rgtti.com from http://wiki.openwrt.org/doc/faq/faq.wireless#how.to.get.a.list.of.connected.clients
 
+chkcmd() {
+  which $1 > /dev/null || {
+    echo "Error: Command '$1' doesn't exist."
+    exit 1
+  }
+}
+
+chkfile() {
+  test -e $1 || {
+    echo "Error: File or directory '$1' doesn't exist."
+    exit 1
+  }
+}
+
+chkcmd iw
+
+leasefile=/var/lib/misc/dnsmasq.leases
+chkfile $leasefile
+
 echo    "# All connected wifi devices, with IP address,"
 echo    "# hostname (if available), and MAC address."
 printf  "# %-20s %-30s %-20s\n" "IP address" "lease name" "MAC address"
-leasefile=/var/lib/misc/dnsmasq.leases
 # list all wireless network interfaces 
 # (for MAC80211 driver; see wiki article for alternative commands)
 for interface in `iw dev | grep Interface | cut -f 2 -s -d" "`
