remove or improve old scripts

diff --git a/bin/mountinfo b/bin/mountinfo
--- a/bin/mountinfo
+++ b/bin/mountinfo
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 [[ $(uname) = Linux ]] || {
-    echo Error: this command is only for Linux >&2
+    echo "Error: this command is only for Linux" >&2
     exit 1
 }
 mount | grep $(df -P "${1:-.}" | tail -n 1 | awk '{print $1}')
diff --git a/bin/sshmnt b/bin/sshmnt
--- a/bin/sshmnt
+++ b/bin/sshmnt
@@ -1,31 +1,31 @@
 #!/bin/bash
 
-error() {
-    echo '[error]' $@
+function error {
+    echo "[error] $@"
     exit 1
 }
-info() {
-    echo '[info]' $@
+function info {
+    echo "[info] $@"
 }
 
-print_usage() {
-    local prog=$(basename $0)
+function print_usage {
+    local prog=$(basename "$0")
     echo 'Usage:'
     echo
     echo "    \$ $prog <mount_point> <[user@]host:path> [...ssh_args]"
     echo
 }
 
-check_command() {
+function check_command {
     hash "$1" &>/dev/null || error "'$1' is required for this script"
 }
 check_command sshfs
 check_command fusermount
 
-uname=`uname`
-[[ $uname = Linux || $uname = Darwin ]] || error "Invalid OS: $uname"
+declare uname="$(uname)"
+[[ "$uname" = "Linux" || "$uname" = "Darwin" ]] || error "Invalid OS: $uname"
 
-[[ $1 = '-h' || $1 = '--help' ]] && {
+[[ "$1" = '-h' || "$1" = '--help' ]] && {
     print_usage
     exit
 }
@@ -34,28 +34,28 @@ uname=`uname`
     error "Wrong number of arguments: $#"
 }
 
-dir=$1
+declare dir="$1"
 
-try_unmount_dir() {
-    fusermount -u $dir &> /dev/null
+function try_unmount_dir {
+    fusermount -u "$dir" &> /dev/null
 }
 try_unmount_dir && info "Unmounted: $dir"
 
 shift
-full_dir_path="$(realpath $dir)"
+declare full_dir_path="$(realpath "$dir")"
 
 
-if [[ -d $dir ]]; then
-    new_directory_created=false
-elif mkdir $dir; then
+if [[ -d "$dir" ]]; then
+    declare new_directory_created=false
+elif mkdir "$dir"; then
     info "Created: $full_dir_path"
-    new_directory_created=true
+    declare new_directory_created=true
 else
     error "Cannot create directory"
 fi
 
-try_remove_created_dir() {
-    $new_directory_created && rmdir $dir
+function try_remove_created_dir {
+    "$new_directory_created" && rmdir "$dir"
 }
 
 end() {
@@ -72,8 +72,8 @@ trap end SIGINT
 info 'Press Ctrl-C to unmount'
 
 while true; do
-    sshfs $@ $dir -f &
-    pid=$!
+    sshfs "$@" "$dir" -f &
+    declare pid="$!"
     info "Process: $pid"
     wait
     try_unmount_dir && info "Unmounted: $full_dir_path"
